name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: "django-insecure-test-key-for-ci-1234567890"
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Create static directory
      run: |
        mkdir -p static
    
    - name: Run Tests
      run: |
        python manage.py test
    
    - name: Run Type Checking
      run: |
        mypy .
    
    - name: Run Linting
      run: |
        pylint **/*.py
        flake8 .

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    
    - name: Run Bandit
      run: |
        bandit -r . -x ./tests,./env,./venv

  coverage:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "django-insecure-test-key-for-ci-1234567890"
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install coverage
    
    - name: Create static directory
      run: |
        mkdir -p static
    
    - name: Run Coverage
      run: |
        coverage run manage.py test
        coverage report
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
